# Generated by Django 5.2.12 on 2026-03-15 11:25

from django.db import migrations, models

import events.models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_emailsettings_alter_weatherdata_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["title"],
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
            },
        ),
        migrations.AlterModelOptions(
            name="eventimage",
            options={
                "verbose_name": "Изображение мероприятия",
                "verbose_name_plural": "Изображения мероприятий",
            },
        ),
        migrations.AlterModelOptions(
            name="weatherdata",
            options={"verbose_name": "Данные погоды", "verbose_name_plural": "Данные погоды"},
        ),
        migrations.AlterField(
            model_name="emailsettings",
            name="message_template",
            field=models.TextField(
                default=events.models.get_default_email_message, verbose_name="Текст письма"
            ),
        ),
    ]
